/**
 * Helper to get responsive image URLs for Cloudflare R2 uploads
 * generated by our Sharp pipeline on the backend.
 * 
 * @param {string} url - The original image URL (e.g. from R2)
 * @param {'thumbnail' | 'medium' | 'original'} size - Desired size variant
 * @returns {string} The URL to the appropriately sized image
 */
export const getOptimizedImageUrl = (url, size = 'original') => {
  if (!url) return '';
  
  // If it's not our R2 bucket, or it's a non-image file type, or it's a GIF (which we don't resize), return original
  if (!url.includes('r2.dev') || url.endsWith('.gif') || url.endsWith('.mp4') || url.endsWith('.webm')) {
    return url;
  }

  // We append variants to the end of the filename in the backend
  if (size === 'thumbnail') {
    return `${url}_400.webp`;
  }
  
  if (size === 'medium') {
    return `${url}_800.webp`;
  }

  return url;
};
