/**
 * Stable machine-readable error codes.
 * Frontend and mobile clients switch on these — never on message strings.
 * Add new codes here before adding them to throws.
 */
export const ERROR_CODES = {
  // Auth
  REGISTRATION_TOKEN_MISSING: "REGISTRATION_TOKEN_MISSING",
  REGISTRATION_TOKEN_INVALID: "REGISTRATION_TOKEN_INVALID",
  REGISTRATION_TOKEN_USED: "REGISTRATION_TOKEN_USED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",

  // Booking
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_CANNOT_CANCEL: "BOOKING_CANNOT_CANCEL",
  CANCELLATION_WINDOW_EXPIRED: "CANCELLATION_WINDOW_EXPIRED",
  INSUFFICIENT_WALLET_BALANCE: "INSUFFICIENT_WALLET_BALANCE",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",

  // Turf
  TURF_NOT_FOUND: "TURF_NOT_FOUND",

  // Game
  GAME_NOT_FOUND: "GAME_NOT_FOUND",
  GAME_FULL: "GAME_FULL",
  ALREADY_JOINED: "ALREADY_JOINED",

  // Scoring
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  MATCH_ALREADY_STARTED: "MATCH_ALREADY_STARTED",
  INNINGS_COMPLETE: "INNINGS_COMPLETE",

  // DB
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  FOREIGN_KEY_VIOLATION: "FOREIGN_KEY_VIOLATION",

  // Generic
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
};
