import request from "supertest";
import app from "../app.js";
import { prisma } from "../config/prisma.js";
import dotenv from "dotenv";
import logger from "../utils/logger.js";
import razorpay from "../config/razorpay.js";
import crypto from "crypto";

dotenv.config();

const ts = Date.now();
const emailUser = `wallet_u_${ts}@kridaz.test`;
const phoneUser = `93333${String(ts).slice(-5)}`;
const userNameUser = `wallet_u_${ts}`;

const emailOwner = `wallet_o_${ts}@kridaz.test`;
const phoneOwner = `94444${String(ts).slice(-5)}`;
const userNameOwner = `wallet_o_${ts}`;

let userToken = "";
let ownerToken = "";
let userId = "";
let ownerUserId = "";
let ownerProfileId = "";

const seedOtp = async (email, phone) => {
  await prisma.oTP.deleteMany({ where: { email } });
  await prisma.oTP.create({
    data: {
      email,
      phone,
      emailOtp: "123456",
      phoneOtp: "123456",
      expiresAt: new Date(Date.now() + 600000),
    },
  });
};

describe("Wallet Module API Integration Tests", () => {
  beforeAll(async () => {
    // Mock Razorpay API methods to prevent actual API calls using native async functions
    razorpay.orders.create = async () => ({
      id: "order_test_123456",
      entity: "order",
      amount: 100000, // paise
      amount_paid: 0,
      amount_due: 100000,
      currency: "INR",
      receipt: `receipt_${Date.now()}`,
      status: "created",
      attempts: 0,
      notes: [],
      created_at: Math.floor(Date.now() / 1000),
    });

    razorpay.orders.fetchPayments = async () => ({
      entity: "collection",
      count: 1,
      items: [
        {
          id: "pay_test_123456",
          entity: "payment",
          amount: 100000,
          currency: "INR",
          status: "captured",
          order_id: "order_test_123456",
          invoice_id: null,
          international: false,
          method: "card",
          amount_refunded: 0,
          refund_status: null,
          captured: true,
          description: "Wallet Top-up",
          card_id: "card_test",
          bank: null,
          wallet: null,
          vpa: null,
          email: emailUser,
          contact: phoneUser,
          fee: 2360,
          tax: 360,
          error_code: null,
          error_description: null,
          created_at: Math.floor(Date.now() / 1000),
        },
      ],
    });

    // Clean up any existing data matching our test emails
    for (const email of [emailUser, emailOwner]) {
      const user = await prisma.user.findFirst({ where: { email } });
      if (user) {
        await prisma.walletTransaction
          .deleteMany({ where: { userId: user.id } })
          .catch(() => {});
        await prisma.wallet
          .deleteMany({ where: { userId: user.id } })
          .catch(() => {});
        await prisma.withdrawalRequest
          .deleteMany({ where: { owner: { userId: user.id } } })
          .catch(() => {});
        await prisma.ownerProfile
          .deleteMany({ where: { userId: user.id } })
          .catch(() => {});
        await prisma.user.delete({ where: { id: user.id } }).catch(() => {});
      }
      await prisma.oTP.deleteMany({ where: { email } }).catch(() => {});
    }

    // Seed OTPs for registration validation
    await seedOtp(emailUser, phoneUser);
    await seedOtp(emailOwner, phoneOwner);

    // Register general USER
    const otpRes_regUser = await request(app)
      .post("/api/user/auth/verify-otp")
      .send({ email: emailUser, phone: phoneUser, otp: "123456" });
    const regUser = await request(app).post("/api/user/auth/register").send({
      name: "Wallet General User",
      email: emailUser,
      username: userNameUser,
      phone: phoneUser,
      gender: "Male",
      location: "Delhi",
      password: "User@Pass123",
      confirmPassword: "User@Pass123",
      otp: "123456",
      phoneOtp: "123456",
      registrationToken: otpRes_regUser.body.registrationToken,
    });

    if (regUser.statusCode === 201) {
      userToken = regUser.body.token;
      userId = regUser.body.user?.id || "";
    } else {
      logger.error("Failed to register general user:", regUser.body);
    }

    // Register turf OWNER using owner auth endpoint
    const regOwner = await request(app).post("/api/owner/auth/register").send({
      name: "Wallet Owner User",
      email: emailOwner,
      phone: phoneOwner,
      password: "Owner@Pass123",
      role: "OWNER",
      gender: "Male",
      location: "Delhi",
      otp: "123456",
      phoneOtp: "123456",
    });

    if (regOwner.statusCode === 201) {
      ownerUserId = regOwner.body.user?.id || "";
      ownerToken = regOwner.body.token;

      // Retrieve ownerProfile automatically generated by registerOwner controller
      const profile = await prisma.ownerProfile.findFirst({
        where: { userId: ownerUserId },
      });
      ownerProfileId = profile?.id || "";
    } else {
      logger.error("Failed to register owner user:", regOwner.body);
    }
  }, 30000);

  afterAll(async () => {
    // Final clean up of test records
    for (const email of [emailUser, emailOwner]) {
      const user = await prisma.user.findFirst({ where: { email } });
      if (user) {
        await prisma.walletTransaction
          .deleteMany({ where: { userId: user.id } })
          .catch(() => {});
        await prisma.wallet
          .deleteMany({ where: { userId: user.id } })
          .catch(() => {});
        await prisma.withdrawalRequest
          .deleteMany({ where: { owner: { userId: user.id } } })
          .catch(() => {});
        await prisma.ownerProfile
          .deleteMany({ where: { userId: user.id } })
          .catch(() => {});
        await prisma.user.delete({ where: { id: user.id } }).catch(() => {});
      }
      await prisma.oTP.deleteMany({ where: { email } }).catch(() => {});
    }
  });

  describe("GET /api/user/wallet/data - Fetch User Wallet Data", () => {
    it("should retrieve clean empty wallet structure for a new user", async () => {
      if (!userToken) return logger.warn("Skipped: no userToken");

      const res = await request(app)
        .get("/api/user/wallet/data")
        .set("Authorization", `Bearer ${userToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body).toHaveProperty("balance");
      expect(res.body).toHaveProperty("usableBalance");
      expect(res.body).toHaveProperty("transactions");
      expect(Array.isArray(res.body.transactions)).toBe(true);
    });
  });

  describe("POST /api/user/wallet/topup/create-order - Create Razorpay topup order", () => {
    it("should reject invalid amount parameters", async () => {
      if (!userToken) return logger.warn("Skipped: no userToken");

      const res = await request(app)
        .post("/api/user/wallet/topup/create-order")
        .set("Authorization", `Bearer ${userToken}`)
        .send({ amount: -100 });

      expect(res.statusCode).toBe(422);
    });

    it("should create razorpay order successfully and store in database as PENDING", async () => {
      if (!userToken) return logger.warn("Skipped: no userToken");

      const res = await request(app)
        .post("/api/user/wallet/topup/create-order")
        .set("Authorization", `Bearer ${userToken}`)
        .send({ amount: 1000 });

      expect(res.statusCode).toBe(200);
      expect(res.body).toHaveProperty("order");
      expect(res.body.order).toHaveProperty("id");
      expect(res.body.order.id).toBe("order_test_123456");

      // Verify db transaction was stored
      const txn = await prisma.walletTransaction.findFirst({
        where: { razorpayOrderId: "order_test_123456", userId: userId },
      });
      expect(txn).toBeDefined();
      expect(Number(txn.amount)).toBe(1000);
      expect(txn.status).toBe("PENDING");
    });
  });

  describe("POST /api/user/wallet/topup/verify - Verify Razorpay payment", () => {
    it("should reject if payment signature is invalid", async () => {
      if (!userToken) return logger.warn("Skipped: no userToken");

      const res = await request(app)
        .post("/api/user/wallet/topup/verify")
        .set("Authorization", `Bearer ${userToken}`)
        .send({
          razorpay_order_id: "order_test_123456",
          razorpay_payment_id: "pay_test_123456",
          razorpay_signature: "wrong_signature",
        });

      expect(res.statusCode).toBe(400);
      expect(res.body.success).toBe(false);

      // Verify db status updated to FAILED
      const txn = await prisma.walletTransaction.findFirst({
        where: { razorpayOrderId: "order_test_123456", userId: userId },
      });
      expect(txn.status).toBe("FAILED");
    });

    it("should accept valid payment verification, credit user and complete status", async () => {
      if (!userToken) return logger.warn("Skipped: no userToken");

      // Create a fresh PENDING transaction to verify successfully
      const freshOrderRes = await request(app)
        .post("/api/user/wallet/topup/create-order")
        .set("Authorization", `Bearer ${userToken}`)
        .send({ amount: 1000 });

      expect(freshOrderRes.statusCode).toBe(200);
      const razorpayOrderId = freshOrderRes.body.order.id;

      // Calculate real HMAC sha256 signature for test validation stability
      const razorpayPaymentId = "pay_fresh_123456";
      const hmac = crypto.createHmac(
        "sha256",
        process.env.RAZORPAY_KEY_SECRET || "razorpay_secret"
      );
      hmac.update(`${razorpayOrderId}|${razorpayPaymentId}`);
      const validSignature = hmac.digest("hex");

      const verifyRes = await request(app)
        .post("/api/user/wallet/topup/verify")
        .set("Authorization", `Bearer ${userToken}`)
        .send({
          razorpay_order_id: razorpayOrderId,
          razorpay_payment_id: razorpayPaymentId,
          razorpay_signature: validSignature,
        });

      if (verifyRes.statusCode !== 200) {
        console.log("DEBUG VERIFY BODY:", JSON.stringify(verifyRes.body));
      }
      expect(verifyRes.statusCode).toBe(200);
      expect(verifyRes.body.success).toBe(true);
      expect(verifyRes.body.balance).toBeGreaterThanOrEqual(1000);

      // Verify transaction database record is SUCCESS
      const updatedTxn = await prisma.walletTransaction.findFirst({
        where: { razorpayOrderId: razorpayOrderId },
        orderBy: { createdAt: "desc" },
      });
      expect(updatedTxn.status).toBe("SUCCESS");
    });
  });

  describe("GET /api/user/wallet/topup/check-status/:orderId - Check webhook/polling status", () => {
    it("should check status successfully through Razorpay API", async () => {
      if (!userToken) return logger.warn("Skipped: no userToken");

      // Create PENDING txn to test status check
      await prisma.walletTransaction.create({
        data: {
          userId: userId,
          amount: 1000,
          type: "TOPUP",
          status: "PENDING",
          description: "Wallet Top-up",
          razorpayOrderId: "order_test_123456_status",
        },
      });

      // Native mock function for fetchPayments in polling check-status route
      razorpay.orders.fetchPayments = async () => ({
        entity: "collection",
        count: 1,
        items: [{ id: "pay_fresh_123", status: "captured" }],
      });

      const res = await request(app)
        .get("/api/user/wallet/topup/check-status/order_test_123456_status")
        .set("Authorization", `Bearer ${userToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.message).toContain("Payment was successful");
    });
  });

  describe("Withdrawal Workflows for Turf Partners (Owner)", () => {
    it("should retrieve clean wallet details for Owner Profile", async () => {
      if (!ownerToken) return logger.warn("Skipped: no ownerToken");

      const res = await request(app)
        .get("/api/owner/wallet/owner/data")
        .set("Authorization", `Bearer ${ownerToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body).toHaveProperty("balance");
      expect(res.body).toHaveProperty("usableBalance");
    });

    it("should reject withdrawal if usable balance is insufficient", async () => {
      if (!ownerToken) return logger.warn("Skipped: no ownerToken");

      const res = await request(app)
        .post("/api/owner/wallet/owner/withdraw")
        .set("Authorization", `Bearer ${ownerToken}`)
        .send({
          amount: 1500,
          bankDetails: { ifsc: "HDFC0001234", accountNumber: "1234567890" },
        });

      expect(res.statusCode).toBe(400);
      expect(res.body.message).toContain("Insufficient usable balance");
    });

    it("should process withdrawal successfully once balance is credited", async () => {
      if (!ownerToken || !ownerProfileId)
        return logger.warn("Skipped: no ownerToken");

      // Seed ownerProfile wallet balance directly using prisma
      await prisma.ownerProfile.update({
        where: { id: ownerProfileId },
        data: { walletBalance: 5000, reservedBalance: 0 },
      });

      const res = await request(app)
        .post("/api/owner/wallet/owner/withdraw")
        .set("Authorization", `Bearer ${ownerToken}`)
        .send({
          amount: 2000,
          bankDetails: { ifsc: "HDFC0001234", accountNumber: "1234567890" },
        });

      expect(res.statusCode).toBe(201);
      expect(res.body.success).toBe(true);
      expect(res.body.request.status).toBe("PENDING");
      expect(res.body.request.amount).toBe(2000);

      // Verify owner profile reserve is updated
      const updatedProfile = await prisma.ownerProfile.findUnique({
        where: { id: ownerProfileId },
      });
      expect(updatedProfile.reservedBalance).toBe(2000);
    });

    it("should fetch withdrawal history successfully for Partner", async () => {
      if (!ownerToken) return logger.warn("Skipped: no ownerToken");

      const res = await request(app)
        .get("/api/owner/wallet/owner/withdrawals")
        .set("Authorization", `Bearer ${ownerToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(Array.isArray(res.body.requests)).toBe(true);
      expect(res.body.requests.length).toBeGreaterThanOrEqual(1);
      expect(res.body.requests[0].amount).toBe(2000);
    });
  });
});
